### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by classita2661** [xinan2/lhdn-einvoice-malaysia-erpnext#2]
hi there,

after running bench --site xxx install-app myinvois, then getting with error internal server error.

**Comment by classita2661** [comment]
ModuleNotFoundError
ModuleNotFoundError: No module named 'qrcode'

Traceback (most recent call last)
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 172, in get_obj_dict_from_paths
obj = frappe.get_module(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 20, in get_response
response = renderer_instance.render()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
self.update_context()
^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
data = self.run_pymodule_method("get_context")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
return method(self.context)
^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/www/login.py", line 61, in get_context
context["signup_form_template"] = frappe.get_template(path).render()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 37, in get_template
return get_jenv().get_template(path)
^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 27, in get_jenv
methods, filters = get_jinja_hooks()
     ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 188, in get_jinja_hooks
method_dict = get_obj_dict_from_paths(methods)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 174, in get_obj_dict_from_paths
obj = frappe.get_attr(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1765, in get_attr
return getattr(get_module(modulename), methodname)
        ^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 172, in get_obj_dict_from_paths
obj = frappe.get_module(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 123, in application
response = get_response()
^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 28, in get_response
response = ErrorPage(exception=e).render()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 96, in get_html
self.setup_template_source()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 151, in setup_template_source
self.source = self.get_raw_template()
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 246, in get_raw_template
return frappe.get_jloader().get_source(frappe.get_jenv(), self.context.template)[0]
                         ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 27, in get_jenv
methods, filters = get_jinja_hooks()
     ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 188, in get_jinja_hooks
method_dict = get_obj_dict_from_paths(methods)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 174, in get_obj_dict_from_paths
obj = frappe.get_attr(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1765, in get_attr
return getattr(get_module(modulename), methodname)
        ^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 172, in get_obj_dict_from_paths
obj = frappe.get_module(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 20, in get_response
response = renderer_instance.render()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 96, in get_html
self.setup_template_source()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 151, in setup_template_source
self.source = self.get_raw_template()
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 246, in get_raw_template
return frappe.get_jloader().get_source(frappe.get_jenv(), self.context.template)[0]
                         ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 27, in get_jenv
methods, filters = get_jinja_hooks()
     ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 188, in get_jinja_hooks
method_dict = get_obj_dict_from_paths(methods)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 174, in get_obj_dict_from_paths
obj = frappe.get_attr(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1765, in get_attr
return getattr(get_module(modulename), methodname)
        ^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 172, in get_obj_dict_from_paths
obj = frappe.get_module(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
During handling of the above exception, another exception occurred:
File "/home/frappe/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
return super().__call__(environ, start_response)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/werkzeug/middleware/shared_data.py", line 249, in __call__
return self.app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/werkzeug/middleware/shared_data.py", line 249, in __call__
return self.app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 79, in application
app(environ, start_response),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/werkzeug/wrappers/request.py", line 190, in application
resp = f(*args[:-2] + (request,))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 132, in application
response = handle_exception(e)
^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 395, in handle_exception
response = get_response("message", http_status_code=http_status_code)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 28, in get_response
response = ErrorPage(exception=e).render()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 96, in get_html
self.setup_template_source()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 151, in setup_template_source
self.source = self.get_raw_template()
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 246, in get_raw_template
return frappe.get_jloader().get_source(frappe.get_jenv(), self.context.template)[0]
                         ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 27, in get_jenv
methods, filters = get_jinja_hooks()
     ^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 188, in get_jinja_hooks
method_dict = get_obj_dict_from_paths(methods)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 174, in get_obj_dict_from_paths
obj = frappe.get_attr(obj_path)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1765, in get_attr
return getattr(get_module(modulename), methodname)
        ^^^^^^^^^^^^^^^^^^^^^^
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1483, in get_module
return importlib.import_module(modulename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/frappe/frappe-bench/apps/myinvois/myinvois/myinvois/sign_invoice.py", line 50, in <module>
import qrcode
ModuleNotFoundError: No module named 'qrcode'

**Comment by mrehan675** [comment]
send your issue on this email rehan.muhamad675@gmail.com

**Comment by mehedi432** [comment]
Please go to your virtual environment of your frappe installation and try to install 'qrcode' through 
`bash
    source env/bin/activate && pip install qrcode
`

**Comment by diniemasjuki** [comment]
is this issue fixed yet ?
i got the same problem after installing.
thanks

**Comment by diniemasjuki** [comment]
okey, i got right.
its missing qrcode plugin in my ubuntu
after the module being install, everything is fine so far.
